### ISSUE TITLE
Fails

### ISSUE THREAD

**Issue by zorkow** [davidaustinm/ptx2svg#1]
Sorry, does not work with:

```
python src/parsesvg.py examples/figure.xml
```

Error is:

```
Traceback (most recent call last):
  File "src/parsesvg.py", line 37, in <module>
    parse(element, fig_count)
  File "src/parsesvg.py", line 34, in parse
    endfigure(output)
  File "/home/sorge-old/git/PreTeXt/ptx2svg/src/ptx2svg.py", line 65, in endfigure
    et.write(filename, pretty_print=True)
  File "src/lxml/etree.pyx", line 2057, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 746, in lxml.etree._tofilelike
  File "src/lxml/serializer.pxi", line 813, in lxml.etree._create_output_buffer
  File "src/lxml/serializer.pxi", line 803, in lxml.etree._create_output_buffer
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by davidaustinm** [comment]
Sorry, I had my paths set up differently on my machine.  Your usage should work now.

**Comment by zorkow** [comment]
Great. Thanks. It works now.
Would you like to come out for a drink?

**Comment by zorkow** [comment]
Next step:
* create a dedicated `.svg` file instead of an `html`
* print out an `xml` structure with the annotations for a navigation structure.
